language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
install:
  - npm ci
script:
  - npm run build
  - npm start -- --silent &
  - $(npm bin)/cypress run
  - kill $(jobs -p) || true
  - npm test
